### ISSUE TITLE
instlantly crash when i add a game, it does add it but the file only like 50 ko (im on mint)

### ISSUE THREAD

**Issue by sanyyyyyy** [mq1/TinyWiiBackupManager#4]

**Comment by mak448a** [comment]
Happens on fedora too

**Comment by mq1** [comment]
Sorry for the late response, I've been a lot busy lately :/

This release https://github.com/mq1/TinyWiiBackupManager/releases/tag/0.3.8 might work, but unfortunately I'm unable to test it as of now

**Comment by mak448a** [comment]
It doesn't crash anymore!
